apps/urls.py
from django.contrib import admin
from django.urls import path, include

import theme.views

urlpatterns = [
    path('', theme.views.base),
    path("quote/", include('quote.urls')),

    path("admin/", admin.site.urls),
]

quote/urls.py
from django.urls import path

from . import views

app_name = 'quote'

urlpatterns = [
    path('newQuote/', views.quote, name="Quote"),
    path('costing/', views.costing, name="Costing"),
]

quote/models.py
from django.db import models

# Create your models here.
# check how to define 1 to many model

theme/models.py
from django.db import models

# Create your models here.

quote/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
def quote(request, template_name = 'Quote.html'):
    return render(request, template_name, {})

def costing(request, template_name = 'Costing.html'):
    return render(request, template_name, {})

theme/views.py
from django.shortcuts import render

# Create your views here.
def base(request, template_name='Base.html'):
    return render(request, template_name)

quote/templates/Costing.html
<h2>Costings</h2>

quote/templates/Customer.html
<h2> Customer Details </h2>
<div>
    <div>
        <label>Name: </label>
        <input></input>
    </div>
    <div>
        <label>Email: </label>
        <input></input>
    </div>
    <div>
        <label>Address: </label>
        <input></input>
    </div>
    <div>
        <label>Contact: </label>
        <input></input>
    </div>
    <div>
        <label>zip code: </label>
        <input></input>
    </div>
</div>

quote/templates/Fabrics.html
<h2> Fabric Details</h2>
    <div>
        <label>Quality: </label>
        <input></input>
    </div>
    <div>
        <h3>Wrap Details:</h3>
        <div>
            <label>Count:</label>
            <input>
            <label>Rate(GST):</label>
            <input>
            <label>GST:</label>
            <input>
            <label>Rate:</label>
            <input disabled>
        </div>
        <h3>Weft Details:</h3>
        <div>
            <label>Count:</label>
            <input>
            <label>Rate(GST):</label>
            <input>
            <label>GST:</label>
            <input>
            <label>Rate:</label>
            <input disabled>
        </div>
        <div>
            <label>Weave:</label>
            <input>
            <label>Width(in):</label>
            <input>
        </div>
        <div>
            <label>EPI:</label>
            <input>
            <label>PPI:</label>
            <input>
            <label>No of Insertion:</label>
            <input>
            <label>Reed Space:</label>
            <input>
        </div>
        <div>
            <label>Shrinkage:</label>
            <input>
            <label>Wastage:</label>
            <input>
            <label>Pick Rate:</label>
            <input>
        </div>
        <div>
            <label>Sizing:</label>
            <input>
            <label>Transportation:</label>
            <input>
            <label>Packaging:</label>
            <input>
        </div>
        <div>
            <label>Rejection(%):</label>
            <input>
            <label>Margin(%):</label>
            <input>
            <label>Commission(%):</label>
            <input>
        </div>
        <div>
            <label>Interest:</label>
            <input>
            <label>Order Quantity(mtrs):</label>
            <input>
        </div>

quote/templates/Quote.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}
    {% include 'Customer.html' %}
    {% include 'Fabrics.html' %}
    {% include 'Costing.html' %}
        <button type="submit">Submit</button>
</form>

{% endblock %}

theme/templates/Base.html
{% load static %}

<html>
<head>
    <title>Ukarde Fabrics</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="content">
        <!-- {% if user.is_authenticated %}
        <div id="user">
            Hello {{ user }}, <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% endif %} -->
        {% include 'navbar.html' %}
            {% block content %}
            {% endblock %}
    </div><!-- content -->

    <div id="footer">
    </div>
</body>
</html>

theme/templates/navbar.html
<div id="header">
    <h1><a href="/">Ukarde Textile Group LOGO</a></h1>
</div><!-- header -->
<div id="navbar">
    <a id="nav-item" href="{% url 'quote:Quote' %}">New Quotation</a><br>
    <!-- <a id="nav-item" href="{% url 'quote:Quote' %}">Fabric Details</a><br>
    <a id="nav-item" href="{% url 'quote:Costing' %}">Costing</a><br>
    <a id="nav-item" href="{% url 'quote:Quote' %}">Placeholder1</a><br> -->
</div>    